/**
 * Internal link integrity.
 *
 * Runs against dist/, so it validates what actually ships rather than what the
 * source intended. A link to a route that does not exist FAILS THE BUILD: it
 * must never reach production and 404 there.
 *
 * A link that resolves only through a redirect declared in firebase.json is a
 * warning rather than an error. It works, but every hop costs a little link
 * equity and it should be repointed at the final destination.
 *
 *   node scripts/verify-links.mjs
 */

import { readFile } from "node:fs/promises";
import { readdirSync, statSync } from "node:fs";
import path from "node:path";

import { DIST, ROOT, listHtmlFiles, requireDist, routeFor } from "./lib/dist.mjs";

requireDist();

/* --- every path the build actually emitted -------------------------------- */

const routes = new Set();

function walkAll(dir) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) {
      walkAll(full);
    } else {
      const rel = path.relative(DIST, full).split(path.sep).join("/");
      /* A page is reachable at its directory route, and every file is also
         reachable at its own literal path. Both are legal link targets. */
      if (rel.endsWith(".html")) routes.add(routeFor(rel));
      routes.add(`/${rel}`);
    }
  }
}
walkAll(DIST);

/* --- the redirect map ------------------------------------------------------ */

const redirectSources = new Set();
try {
  const config = JSON.parse(await readFile(path.join(ROOT, "firebase.json"), "utf8"));
  for (const rule of config.hosting?.redirects ?? []) redirectSources.add(rule.source);
} catch {
  console.warn("  firebase.json not readable, redirect-aware checks skipped.");
}

/* --- scan every emitted page ----------------------------------------------- */

const files = await listHtmlFiles();
const broken = [];
const viaRedirect = [];
let checked = 0;
let assetsChecked = 0;

/**
 * WHAT IS SCANNED, AND WHY IT IS NOT JUST <a>.
 *
 * The obvious version of this check reads anchors, because a broken anchor is
 * the failure everybody pictures. But the failure that actually ships unnoticed
 * is a broken <link> in the <head>: a favicon, an apple-touch-icon, a web
 * manifest or the sitemap. Nothing visibly breaks. The page renders. The only
 * symptom is a blank browser tab, which nobody reports and nobody sees in a
 * screenshot of their own site, because their own browser has the old icon
 * cached.
 *
 * ism50.com declares six such files in src/components/BaseHead.astro, all
 * generated by scripts/make-brand.mjs and committed under public/. Committed
 * generated assets are exactly the kind of thing that goes missing in a
 * rebase, a .gitignore edit or a half-applied patch, so the build asserts they
 * are still there.
 *
 * `<img src>` is scanned for the same reason. Astro's pipeline emits hashed
 * filenames it can be trusted with, but a hand-written public/ path in a
 * component is not checked by anything else.
 */
const PATTERNS = [
  { kind: "anchor", re: /<a\b[^>]*\shref="([^"]+)"/gi },
  { kind: "head link", re: /<link\b[^>]*\shref="([^"]+)"/gi },
  { kind: "image", re: /<img\b[^>]*\ssrc="([^"]+)"/gi },
];

for (const file of files) {
  const html = await readFile(path.join(DIST, file), "utf8");
  const from = routeFor(file);

  for (const { kind, re } of PATTERNS) {
    for (const match of html.matchAll(re)) {
      let href = match[1].trim();

      if (/^(https?:|mailto:|tel:|#|data:)/i.test(href)) continue;
      if (!href.startsWith("/")) continue;

      href = href.split("#")[0].split("?")[0];
      if (!href) continue;
      if (kind === "anchor") checked++;
      else assetsChecked++;

      /* A ROUTE needs a trailing slash on this site. A path with an extension is
         a FILE and keeps exactly what it has: appending a slash to
         /favicon.ico would look for a directory and report a false break. */
      const target = href.endsWith("/") || path.extname(href) ? href : `${href}/`;

      if (routes.has(target) || routes.has(href)) continue;
      if (redirectSources.has(target) || redirectSources.has(href)) {
        viaRedirect.push({ from, href: target });
        continue;
      }
      broken.push({ from, href: target, kind });
    }
  }
}

/* --- report ---------------------------------------------------------------- */

console.log(
  `verify:links   pages ${files.length}, internal links ${checked}, head links and images ${assetsChecked}`
);

if (viaRedirect.length) {
  const grouped = new Map();
  for (const item of viaRedirect) grouped.set(item.href, (grouped.get(item.href) ?? 0) + 1);
  console.warn("\n  warning, these resolve only through a redirect hop:");
  for (const [href, count] of [...grouped].sort((a, b) => b[1] - a[1]).slice(0, 10)) {
    console.warn(`    ${String(count).padStart(4)}x  ${href}`);
  }
}

if (broken.length) {
  const grouped = new Map();
  for (const item of broken) {
    if (!grouped.has(item.href)) grouped.set(item.href, []);
    grouped.get(item.href).push(item.from);
  }
  console.error("\nBROKEN INTERNAL LINKS. These would 404 in production.\n");
  for (const [href, sources] of [...grouped].sort((a, b) => b[1].length - a[1].length)) {
    console.error(`  ${href}   (${sources.length} page${sources.length > 1 ? "s" : ""})`);
    for (const source of sources.slice(0, 3)) console.error(`      from ${source}`);
    if (sources.length > 3) console.error(`      and ${sources.length - 3} more`);
  }
  process.exit(1);
}

console.log("verify:links   all internal links resolve.");
